"""
Image schemas.
Pydantic models for image upload and management.
"""
from datetime import datetime
from typing import Any

from pydantic import BaseModel, Field

from app.models.image import ImageStatus, ImageType


# ── Base ──────────────────────────────────────────────────────────

class ImageBase(BaseModel):
    image_type: ImageType | None = None
    status: ImageStatus = ImageStatus.pending
    analysis_result: str | dict[str, Any] | None = None
    domain: str | None = None
    view: str | None = None


# ── Create ────────────────────────────────────────────────────────

class ImageCreate(ImageBase):
    """
    Used internally when creating image record directly.
    file_path is optional — generated by service if not provided.
    """
    user_id: int
    file_path: str | None = None
    s3_key: str | None = None
    url: str | None = None
    mime_type: str | None = None
    file_size: int | None = None


# ── Update ────────────────────────────────────────────────────────

class ImageUpdate(BaseModel):
    """Fields that can be updated on an existing image."""
    analysis_result: str | dict[str, Any] | None = None
    status: ImageStatus | None = None
    image_type: ImageType | None = None
    domain: str | None = None
    view: str | None = None


# ── Output ────────────────────────────────────────────────────────

class ImageOut(BaseModel):
    """Full image response returned to client."""
    id: int
    user_id: int

    # ── Storage ───────────────────────────────────────────────
    file_path: str | None = None
    s3_key: str | None = None
    url: str | None = None
    mime_type: str | None = None
    file_size: int | None = None

    # ── Metadata ──────────────────────────────────────────────
    image_type: ImageType
    status: ImageStatus
    domain: str | None = None
    view: str | None = None

    # ── Analysis ──────────────────────────────────────────────
    analysis_result: str | dict[str, Any] | None = None
    error_message: str | None = None

    # ── Timestamps ────────────────────────────────────────────
    uploaded_at: datetime
    processed_at: datetime | None = None
    updated_at: datetime

    model_config = {"from_attributes": True}


class ImageUrlOut(BaseModel):
    """
     Added: Response for GET /{image_id}/url endpoint.
    """
    image_id: int
    url: str
    expires_in: int = Field(
        ...,
        ge=60,
        le=86400,
        description="URL expiry in seconds (60s–24h)"
    )

    model_config = {
        "json_schema_extra": {
            "example": {
                "image_id": 42,
                "url": "https://s3.amazonaws.com/bucket/...",
                "expires_in": 3600
            }
        }
    }

