"""initial

Revision ID: 0183cd7270fe
Revises: 
Create Date: 2026-01-20 12:17:52.428470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0183cd7270fe'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domain_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=50), nullable=False),
    sa.Column('question', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('constraints', sa.JSON(), nullable=True),
    sa.Column('seq', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain', 'question', name='uq_domain_question'),
    sa.UniqueConstraint('domain', 'seq', name='uq_domain_seq')
    )
    op.create_index(op.f('ix_domain_questions_domain'), 'domain_questions', ['domain'], unique=False)
    op.create_index(op.f('ix_domain_questions_id'), 'domain_questions', ['id'], unique=False)
    op.create_index(op.f('ix_domain_questions_seq'), 'domain_questions', ['seq'], unique=False)
    op.create_index('ix_domain_seq', 'domain_questions', ['domain', 'seq'], unique=False)
    op.create_table('onboarding_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('step', sa.String(length=50), nullable=False),
    sa.Column('question', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('constraints', sa.JSON(), nullable=True),
    sa.Column('seq', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('step', 'question', name='uq_onboarding_step_question'),
    sa.UniqueConstraint('step', 'seq', name='uq_onboarding_step_seq')
    )
    op.create_index(op.f('ix_onboarding_questions_id'), 'onboarding_questions', ['id'], unique=False)
    op.create_index(op.f('ix_onboarding_questions_seq'), 'onboarding_questions', ['seq'], unique=False)
    op.create_index(op.f('ix_onboarding_questions_step'), 'onboarding_questions', ['step'], unique=False)
    op.create_index('ix_step_seq', 'onboarding_questions', ['step', 'seq'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('provider', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_verified', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('google_sub', sa.String(length=255), nullable=True),
    sa.Column('google_picture', sa.String(length=512), nullable=True),
    sa.Column('last_google_id_token', sa.String(length=2048), nullable=True),
    sa.Column('last_apple_id_token', sa.String(length=2048), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('profile_image', sa.String(length=255), nullable=True),
    sa.Column('notifications_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('onboarding_complete', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('selected_domain', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_provider'), 'users', ['provider'], unique=False)
    op.create_table('domain_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=50), nullable=False),
    sa.Column('answer', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['domain_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_answers_domain'), 'domain_answers', ['domain'], unique=False)
    op.create_index(op.f('ix_domain_answers_id'), 'domain_answers', ['id'], unique=False)
    op.create_index(op.f('ix_domain_answers_user_id'), 'domain_answers', ['user_id'], unique=False)
    op.create_index('ix_question_user', 'domain_answers', ['question_id', 'user_id'], unique=False)
    op.create_index('ix_user_domain', 'domain_answers', ['user_id', 'domain'], unique=False)
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('image_type', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('analysis_result', sa.JSON(), nullable=True),
    sa.Column('domain', sa.String(length=50), nullable=True),
    sa.Column('view', sa.String(length=50), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_images_domain'), 'images', ['domain'], unique=False)
    op.create_index(op.f('ix_images_id'), 'images', ['id'], unique=False)
    op.create_index(op.f('ix_images_image_type'), 'images', ['image_type'], unique=False)
    op.create_index(op.f('ix_images_status'), 'images', ['status'], unique=False)
    op.create_index(op.f('ix_images_user_id'), 'images', ['user_id'], unique=False)
    op.create_index(op.f('ix_images_view'), 'images', ['view'], unique=False)
    op.create_index('ix_user_domain_view', 'images', ['user_id', 'domain', 'view'], unique=False)
    op.create_index('ix_user_status', 'images', ['user_id', 'status'], unique=False)
    op.create_index('ix_user_type', 'images', ['user_id', 'image_type'], unique=False)
    op.create_table('insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_insight_user_category', 'insights', ['user_id', 'category'], unique=False)
    op.create_index(op.f('ix_insights_category'), 'insights', ['category'], unique=False)
    op.create_index(op.f('ix_insights_id'), 'insights', ['id'], unique=False)
    op.create_index(op.f('ix_insights_user_id'), 'insights', ['user_id'], unique=False)
    op.create_table('onboarding_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('selected_domain', sa.String(length=50), nullable=True),
    sa.Column('is_paid', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('payment_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onboarding_sessions_selected_domain'), 'onboarding_sessions', ['selected_domain'], unique=False)
    op.create_index(op.f('ix_onboarding_sessions_user_id'), 'onboarding_sessions', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_subscriptions_status'), 'subscriptions', ['status'], unique=False)
    op.create_table('onboarding_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.JSON(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['onboarding_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['onboarding_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onboarding_answers_id'), 'onboarding_answers', ['id'], unique=False)
    op.create_index('ix_session_question', 'onboarding_answers', ['session_id', 'question_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_session_question', table_name='onboarding_answers')
    op.drop_index(op.f('ix_onboarding_answers_id'), table_name='onboarding_answers')
    op.drop_table('onboarding_answers')
    op.drop_index(op.f('ix_subscriptions_status'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_onboarding_sessions_user_id'), table_name='onboarding_sessions')
    op.drop_index(op.f('ix_onboarding_sessions_selected_domain'), table_name='onboarding_sessions')
    op.drop_table('onboarding_sessions')
    op.drop_index(op.f('ix_insights_user_id'), table_name='insights')
    op.drop_index(op.f('ix_insights_id'), table_name='insights')
    op.drop_index(op.f('ix_insights_category'), table_name='insights')
    op.drop_index('ix_insight_user_category', table_name='insights')
    op.drop_table('insights')
    op.drop_index('ix_user_type', table_name='images')
    op.drop_index('ix_user_status', table_name='images')
    op.drop_index('ix_user_domain_view', table_name='images')
    op.drop_index(op.f('ix_images_view'), table_name='images')
    op.drop_index(op.f('ix_images_user_id'), table_name='images')
    op.drop_index(op.f('ix_images_status'), table_name='images')
    op.drop_index(op.f('ix_images_image_type'), table_name='images')
    op.drop_index(op.f('ix_images_id'), table_name='images')
    op.drop_index(op.f('ix_images_domain'), table_name='images')
    op.drop_table('images')
    op.drop_index('ix_user_domain', table_name='domain_answers')
    op.drop_index('ix_question_user', table_name='domain_answers')
    op.drop_index(op.f('ix_domain_answers_user_id'), table_name='domain_answers')
    op.drop_index(op.f('ix_domain_answers_id'), table_name='domain_answers')
    op.drop_index(op.f('ix_domain_answers_domain'), table_name='domain_answers')
    op.drop_table('domain_answers')
    op.drop_index(op.f('ix_users_provider'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_step_seq', table_name='onboarding_questions')
    op.drop_index(op.f('ix_onboarding_questions_step'), table_name='onboarding_questions')
    op.drop_index(op.f('ix_onboarding_questions_seq'), table_name='onboarding_questions')
    op.drop_index(op.f('ix_onboarding_questions_id'), table_name='onboarding_questions')
    op.drop_table('onboarding_questions')
    op.drop_index('ix_domain_seq', table_name='domain_questions')
    op.drop_index(op.f('ix_domain_questions_seq'), table_name='domain_questions')
    op.drop_index(op.f('ix_domain_questions_id'), table_name='domain_questions')
    op.drop_index(op.f('ix_domain_questions_domain'), table_name='domain_questions')
    op.drop_table('domain_questions')
    # ### end Alembic commands ###
