"""add_score_to_insights

Revision ID: 1e7870d52356
Revises: e4b8e528fb0f
Create Date: 2026-03-05 09:41:23.226086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e7870d52356'
down_revision: Union[str, None] = 'e4b8e528fb0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('insights', sa.Column('score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('insights', 'score')
    # ### end Alembic commands ###
