"""Cleaned models for Production

Revision ID: 63ef7c1b17c9
Revises: 
Create Date: 2026-01-09 15:56:31.333076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '63ef7c1b17c9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('domain_answers', 'completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.create_index('ix_question_user', 'domain_answers', ['question_id', 'user_id'], unique=False)
    op.create_index('ix_user_domain', 'domain_answers', ['user_id', 'domain'], unique=False)
    op.alter_column('domain_questions', 'type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.create_index('ix_domain_seq', 'domain_questions', ['domain', 'seq'], unique=False)
    op.create_unique_constraint('uq_domain_seq', 'domain_questions', ['domain', 'seq'])
    op.alter_column('images', 'image_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.create_index('ix_user_status', 'images', ['user_id', 'status'], unique=False)
    op.create_index('ix_user_type', 'images', ['user_id', 'image_type'], unique=False)
    op.create_index('ix_insight_user_category', 'insights', ['user_id', 'category'], unique=False)
    op.alter_column('onboarding_answers', 'completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.create_index('ix_session_question', 'onboarding_answers', ['session_id', 'question_id'], unique=False)
    op.alter_column('onboarding_questions', 'step',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.create_index('ix_step_seq', 'onboarding_questions', ['step', 'seq'], unique=False)
    op.create_unique_constraint('uq_onboarding_step_seq', 'onboarding_questions', ['step', 'seq'])
    op.alter_column('onboarding_sessions', 'selected_domain',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('subscriptions', 'plan',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.create_index(op.f('ix_subscriptions_status'), 'subscriptions', ['status'], unique=False)
    op.drop_column('users', 'goal')
    op.drop_column('users', 'payment_confirmed_at')
    op.drop_column('users', 'payment_method')
    op.drop_column('users', 'goal_selected')
    op.drop_column('users', 'is_paid')
    op.drop_column('users', 'subscription_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subscription_status', sa.VARCHAR(length=20), server_default=sa.text("'inactive'::character varying"), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('is_paid', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('goal_selected', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('payment_method', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('payment_confirmed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('goal', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_subscriptions_status'), table_name='subscriptions')
    op.alter_column('subscriptions', 'plan',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('onboarding_sessions', 'selected_domain',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.drop_constraint('uq_onboarding_step_seq', 'onboarding_questions', type_='unique')
    op.drop_index('ix_step_seq', table_name='onboarding_questions')
    op.alter_column('onboarding_questions', 'step',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_index('ix_session_question', table_name='onboarding_answers')
    op.alter_column('onboarding_answers', 'completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.drop_index('ix_insight_user_category', table_name='insights')
    op.drop_index('ix_user_type', table_name='images')
    op.drop_index('ix_user_status', table_name='images')
    op.alter_column('images', 'image_type',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_constraint('uq_domain_seq', 'domain_questions', type_='unique')
    op.drop_index('ix_domain_seq', table_name='domain_questions')
    op.alter_column('domain_questions', 'type',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_index('ix_user_domain', table_name='domain_answers')
    op.drop_index('ix_question_user', table_name='domain_answers')
    op.alter_column('domain_answers', 'completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    # ### end Alembic commands ###
