"""Updated all the models

Revision ID: 996cc11efbe5
Revises: 0183cd7270fe
Create Date: 2026-02-18 15:09:25.042226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '996cc11efbe5'
down_revision: Union[str, None] = '0183cd7270fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # ── Domain Tables ─────────────────────────────────────────
    # Fill NULL before setting NOT NULL
    op.execute("UPDATE domain_answers SET updated_at = CURRENT_TIMESTAMP WHERE updated_at IS NULL")
    op.alter_column('domain_answers', 'updated_at',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    server_default=sa.text('now()'),
                    nullable=False)
    op.create_unique_constraint('uq_user_question_answer', 'domain_answers', ['user_id', 'question_id'])

    op.alter_column('domain_questions', 'seq',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.execute("UPDATE domain_questions SET updated_at = CURRENT_TIMESTAMP WHERE updated_at IS NULL")
    op.alter_column('domain_questions', 'updated_at',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    server_default=sa.text('now()'),
                    nullable=False)

    # ── Images Table ──────────────────────────────────────────
    op.add_column('images', sa.Column('s3_key', sa.String(length=512), nullable=True))
    op.add_column('images', sa.Column('url', sa.String(length=1024), nullable=True))
    op.add_column('images', sa.Column('mime_type', sa.String(length=100), nullable=True))
    op.add_column('images', sa.Column('file_size', sa.Integer(), nullable=True))
    op.add_column('images', sa.Column('error_message', sa.String(length=512), nullable=True))
    op.alter_column('images', 'file_path',
                    existing_type=sa.VARCHAR(length=255),
                    type_=sa.String(length=512),
                    existing_nullable=False)
    op.alter_column('images', 'image_type',
                    existing_type=sa.VARCHAR(length=20),
                    nullable=False)
    op.execute("UPDATE images SET updated_at = uploaded_at WHERE updated_at IS NULL")
    op.alter_column('images', 'updated_at',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    server_default=sa.text('now()'),
                    nullable=False)

    # ── Insights Table ────────────────────────────────────────
    op.add_column('insights', sa.Column('is_read', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.execute("UPDATE insights SET updated_at = created_at WHERE updated_at IS NULL")
    op.alter_column('insights', 'updated_at',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    server_default=sa.text('now()'),
                    nullable=False)
    op.create_index('ix_insight_user_read', 'insights', ['user_id', 'is_read'], unique=False)

    # ── Onboarding Tables ─────────────────────────────────────
    # Add created_at column FIRST
    op.add_column('onboarding_answers',
                  sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # Now we can use it to fill updated_at
    op.execute("UPDATE onboarding_answers SET updated_at = created_at WHERE updated_at IS NULL")
    op.alter_column('onboarding_answers', 'updated_at',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    server_default=sa.text('now()'),
                    nullable=False)

    op.execute("UPDATE onboarding_questions SET updated_at = CURRENT_TIMESTAMP WHERE updated_at IS NULL")
    op.alter_column('onboarding_questions', 'updated_at',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    server_default=sa.text('now()'),
                    nullable=False)

    # ✅ CRITICAL: Make user_id nullable for anonymous sessions
    op.alter_column('onboarding_sessions', 'user_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)

    op.execute("UPDATE onboarding_sessions SET updated_at = created_at WHERE updated_at IS NULL")
    op.alter_column('onboarding_sessions', 'updated_at',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    server_default=sa.text('now()'),
                    nullable=False)
    op.drop_constraint('onboarding_sessions_user_id_fkey', 'onboarding_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'onboarding_sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ── Refresh Tokens Table ──────────────────────────────────
    op.add_column('refresh_tokens',
                  sa.Column('is_revoked', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('refresh_tokens', sa.Column('device_info', sa.String(length=255), nullable=True))
    op.alter_column('refresh_tokens', 'token',
                    existing_type=sa.VARCHAR(length=255),
                    type_=sa.String(length=2048),
                    existing_nullable=False)
    op.execute("UPDATE refresh_tokens SET updated_at = created_at WHERE updated_at IS NULL")
    op.alter_column('refresh_tokens', 'updated_at',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    server_default=sa.text('now()'),
                    nullable=False)
    op.drop_constraint('refresh_tokens_token_key', 'refresh_tokens', type_='unique')
    op.create_index('ix_refresh_token_lookup', 'refresh_tokens', ['token'], unique=False)
    op.create_index('ix_refresh_token_user', 'refresh_tokens', ['user_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)

    # ── Subscriptions Table ───────────────────────────────────
    op.add_column('subscriptions', sa.Column('stripe_customer_id', sa.String(length=255), nullable=True))
    op.add_column('subscriptions', sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True))
    op.add_column('subscriptions', sa.Column('trial_end', sa.DateTime(timezone=True), nullable=True))
    op.add_column('subscriptions', sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('subscriptions', 'payment_id',
                    existing_type=sa.VARCHAR(length=100),
                    type_=sa.String(length=255),
                    existing_nullable=True)
    op.execute("UPDATE subscriptions SET updated_at = created_at WHERE updated_at IS NULL")
    op.alter_column('subscriptions', 'updated_at',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    server_default=sa.text('now()'),
                    nullable=False)
    op.create_index('ix_subscription_status', 'subscriptions', ['status'], unique=False)
    op.create_index('ix_subscription_user', 'subscriptions', ['user_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_stripe_customer_id'), 'subscriptions', ['stripe_customer_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_stripe_subscription_id'), 'subscriptions', ['stripe_subscription_id'],
                    unique=False)

    # ── Users Table ───────────────────────────────────────────
    op.add_column('users', sa.Column('apple_sub', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('last_login', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('users', 'profile_image',
                    existing_type=sa.VARCHAR(length=255),
                    type_=sa.String(length=512),
                    existing_nullable=True)
    op.execute("UPDATE users SET updated_at = created_at WHERE updated_at IS NULL")
    op.alter_column('users', 'updated_at',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    server_default=sa.text('now()'),
                    nullable=False)
    op.create_index(op.f('ix_users_apple_sub'), 'users', ['apple_sub'], unique=False)
    op.create_index(op.f('ix_users_google_sub'), 'users', ['google_sub'], unique=False)
    op.drop_column('users', 'selected_domain')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # ── Users Table ───────────────────────────────────────────
    op.add_column('users', sa.Column('selected_domain', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_google_sub'), table_name='users')
    op.drop_index(op.f('ix_users_apple_sub'), table_name='users')
    op.alter_column('users', 'updated_at',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    server_default=None,
                    nullable=True)
    op.alter_column('users', 'profile_image',
                    existing_type=sa.String(length=512),
                    type_=sa.VARCHAR(length=255),
                    existing_nullable=True)
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'apple_sub')

    # ── Subscriptions Table ───────────────────────────────────
    op.drop_index(op.f('ix_subscriptions_stripe_subscription_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_stripe_customer_id'), table_name='subscriptions')
    op.drop_index('ix_subscription_user', table_name='subscriptions')
    op.drop_index('ix_subscription_status', table_name='subscriptions')
    op.alter_column('subscriptions', 'updated_at',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    server_default=None,
                    nullable=True)
    op.alter_column('subscriptions', 'payment_id',
                    existing_type=sa.String(length=255),
                    type_=sa.VARCHAR(length=100),
                    existing_nullable=True)
    op.drop_column('subscriptions', 'cancelled_at')
    op.drop_column('subscriptions', 'trial_end')
    op.drop_column('subscriptions', 'stripe_subscription_id')
    op.drop_column('subscriptions', 'stripe_customer_id')

    # ── Refresh Tokens Table ──────────────────────────────────
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_index('ix_refresh_token_user', table_name='refresh_tokens')
    op.drop_index('ix_refresh_token_lookup', table_name='refresh_tokens')
    op.create_unique_constraint('refresh_tokens_token_key', 'refresh_tokens', ['token'])
    op.alter_column('refresh_tokens', 'updated_at',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    server_default=None,
                    nullable=True)
    op.alter_column('refresh_tokens', 'token',
                    existing_type=sa.String(length=2048),
                    type_=sa.VARCHAR(length=255),
                    existing_nullable=False)
    op.drop_column('refresh_tokens', 'device_info')
    op.drop_column('refresh_tokens', 'is_revoked')

    # ── Onboarding Tables ─────────────────────────────────────
    op.drop_constraint(None, 'onboarding_sessions', type_='foreignkey')
    op.create_foreign_key('onboarding_sessions_user_id_fkey', 'onboarding_sessions', 'users', ['user_id'], ['id'],
                          ondelete='SET NULL')

    # ✅ CRITICAL: Revert user_id to NOT NULL (clean up anonymous sessions first)
    op.execute("DELETE FROM onboarding_sessions WHERE user_id IS NULL")
    op.alter_column('onboarding_sessions', 'user_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)

    op.alter_column('onboarding_sessions', 'updated_at',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    server_default=None,
                    nullable=True)
    op.alter_column('onboarding_questions', 'updated_at',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    server_default=None,
                    nullable=True)
    op.alter_column('onboarding_answers', 'updated_at',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    server_default=None,
                    nullable=True)
    op.drop_column('onboarding_answers', 'created_at')

    # ── Insights Table ────────────────────────────────────────
    op.drop_index('ix_insight_user_read', table_name='insights')
    op.alter_column('insights', 'updated_at',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    server_default=None,
                    nullable=True)
    op.drop_column('insights', 'is_read')

    # ── Images Table ──────────────────────────────────────────
    op.alter_column('images', 'updated_at',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    server_default=None,
                    nullable=True)
    op.alter_column('images', 'image_type',
                    existing_type=sa.VARCHAR(length=20),
                    nullable=True)
    op.alter_column('images', 'file_path',
                    existing_type=sa.String(length=512),
                    type_=sa.VARCHAR(length=255),
                    existing_nullable=False)
    op.drop_column('images', 'error_message')
    op.drop_column('images', 'file_size')
    op.drop_column('images', 'mime_type')
    op.drop_column('images', 'url')
    op.drop_column('images', 's3_key')

    # ── Domain Tables ─────────────────────────────────────────
    op.alter_column('domain_questions', 'updated_at',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    server_default=None,
                    nullable=True)
    op.alter_column('domain_questions', 'seq',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.drop_constraint('uq_user_question_answer', 'domain_answers', type_='unique')
    op.alter_column('domain_answers', 'updated_at',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    server_default=None,
                    nullable=True)
    # ### end Alembic commands ###

